/**
 * SendOrderButton.tsx — red "Send Order" button that opens the user's
 * email client with a pre-filled design summary ready to send to a
 * solar vendor or internal approval chain.
 */

import { useTranslation } from 'react-i18next';
import { useApp } from '../store/useApp';

export function SendOrderButton() {
  const { t } = useTranslation();
  const { state } = useApp();
  const { systemDesign, selectedPanel, selectedInverter, selectedBattery, userNotes } = state;

  if (!systemDesign || !selectedPanel || !selectedInverter || !selectedBattery) return null;

  const p = systemDesign.profile;
  const c = systemDesign.capexBreakdown;
  const f = systemDesign.financials;
  const pan = selectedPanel;
  const inv = selectedInverter;
  const bat = selectedBattery;
  const fmt = (n: number) => n.toLocaleString(undefined, { maximumFractionDigits: 0 });

  function handleSend() {
    const subject = `SolarBrain Order — ${p.userType} · ${p.regionName} · ${fmt(c.totalSar)} SAR`;

    const lines = [
      `SolarBrain System Design Order`,
      `================================`,
      ``,
      `Facility Profile:`,
      `  Type: ${p.userType}`,
      `  Region: ${p.regionName}`,
      `  Grid: ${p.gridScenario}`,
      `  Monthly bill: ${fmt(p.monthlyBillSar)} SAR`,
      `  Peak load: ${p.peakLoadKw} kW`,
      ``,
      `Selected Components:`,
      `  Panel: ${pan.brand} ${pan.model}`,
      `    ${pan.actualKwp} kWp (${pan.unitsRequired}× ${pan.powerWp}W)`,
      `  Inverter: ${inv.brand} ${inv.model}`,
      `    ${inv.actualKw} kW (${inv.unitsRequired}× ${inv.capacityKw}kW)`,
      `  Battery: ${bat.brand} ${bat.model}`,
      `    ${bat.actualKwh} kWh (${bat.unitsRequired}× ${bat.capacityKwh}kWh)`,
      ``,
      `Financial Summary:`,
      `  Total CAPEX: ${fmt(c.totalSar)} SAR`,
      `    Panels: ${fmt(c.panelsSar)} SAR`,
      `    Inverter: ${fmt(c.inverterSar)} SAR`,
      `    Battery: ${fmt(c.batterySar)} SAR`,
      `    Protection: ${fmt(c.protectionSar)} SAR`,
      `    BoS: ${fmt(c.bosSar)} SAR`,
      `  Monthly savings: ${fmt(f.monthlySavingsSar)} SAR`,
      `  Break-even: ${f.breakEvenYear ? `Year ${f.breakEvenYear}` : 'Beyond 10 years'}`,
      `  10-year net benefit: ${fmt(f.net10yrBenefitSar)} SAR`,
    ];

    if (userNotes) {
      lines.push(``, `Customer Notes:`, `  ${userNotes}`);
    }

    lines.push(``, `---`, `Generated by SolarBrain · solarbrain.app`);

    const body = lines.join('\n');
    const mailto = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(mailto, '_blank');
  }

  return (
    <button type="button" className="btn btn--send" onClick={handleSend}>
      ✉ {t('results.sendOrder')}
    </button>
  );
}
